# Generated by Django 4.0.5 on 2022-06-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_catalogelement_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='version_start_date',
            field=models.DateField(verbose_name='Дата версии'),
        ),
    ]
